### ISSUE TITLE
Lower durability on usage

### ISSUE THREAD

**Issue by DuckyOnThatQuack** [theMani-kh/qb-durability#1]
Is there a way to make certain items like lock picks lose durability when used?

**Comment by theMani-kh** [comment]
Hi, It will be add in new update. tnx for your idea. <3

**Comment by theMani-kh** [comment]
Hi, added export and event, you can use them.

**Comment by DuckyOnThatQuack** [comment]
Thanks for adding the feature! Is it cool if you add an example? Sorry I’m still quite new to exports and such.

**Comment by theMani-kh** [comment]
Sure, For example if you want use decay after use item you should use export in server side,

QBCore.Functions.CreateUseableItem("lockpick", function(source, item)
    -- lockpick Trigger Events
    exports['qb-durability']:DecayItem(source, "lockpick", 20, item.slot)
end)

and if you want to use decay when lockpick vehicle or something else in client side you can use server event. I use ps-ui circle minigame for example

exports['ps-ui']:Circle(function(success)
    if success then
        print("success")
	else
		print("fail")
		TriggerServerEvent("qb-durability:server:Decay", "lockpick", 20)
	end
end, 2, 20) -- NumberOfCircles, MS

in export and event, slot is optional.

good luck. <3
